#pragma once
#include "../../localLibs/queue/queueDeclaration.h"

// Note: Use a Space to separate numbers.
// Note: It can parse only "+ - * /" operators and round brackets if it is in an infix form
// Note: You must pass numbers with the negative value (for exaple, A) in this way: "0 - B", where 'B' = abs(A)

int stringPostfixCalculator(char *rawPostfixExpression, int *errorCode);
int queuePostfixCalculator(Queue *postfixExpression, int *errorCode);
// Parameter: pass Queue generated by sortingMachine() from sortingStation.c

int calculator(char *infixExpression, int *errorCode);